version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop_old_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/pull_image.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
